filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit --colors --verbose
    php_sim:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_changetracking:
        enabled: true

before_commands:
    - "composer install --prefer-source"
